from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    SubscriptionPlanViewSet,
    UserSubscriptionViewSet,
    PaymentTransactionViewSet,
    StripeWebhookView
)

app_name = 'payments'

router = DefaultRouter()
router.register(r'plans', SubscriptionPlanViewSet, basename='subscription-plan')
router.register(r'subscriptions', UserSubscriptionViewSet, basename='user-subscription') # For custom actions
router.register(r'transactions', PaymentTransactionViewSet, basename='payment-transaction')

urlpatterns = [
    path('', include(router.urls)),
    path('stripe-webhook/', StripeWebhookView.as_view(), name='stripe-webhook'),

    # Note: The custom actions in UserSubscriptionViewSet like 'my-subscription',
    # 'create-subscription', and 'cancel-subscription' will be automatically
    # routed by DefaultRouter if they are correctly defined with @action.
    # For example:
    # /api/payments/subscriptions/my-subscription/
    # /api/payments/subscriptions/create-subscription/
    # /api/payments/subscriptions/cancel-subscription/
]

# Example of how URLs generated by the router might look:
# /api/payments/plans/
# /api/payments/plans/{plan_id}/

# /api/payments/subscriptions/my-subscription/ (GET - custom action)
# /api/payments/subscriptions/create-subscription/ (POST - custom action)
# /api/payments/subscriptions/cancel-subscription/ (POST - custom action)
# If UserSubscriptionViewSet were a ModelViewSet for a specific subscription ID,
# it would also have:
# /api/payments/subscriptions/{subscription_id}/ (GET, PUT, PATCH, DELETE if enabled)

# /api/payments/transactions/
# /api/payments/transactions/{transaction_id}/

# And the explicitly defined webhook:
# /api/payments/stripe-webhook/ (POST)
